---
# configuration for GitHub Actions
name: rerobots Rust client library tests
on:
    push:
    pull_request:
jobs:
    build:
        name: Build
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v2
            - name: Prepare to build
              run: |
                mkdir keys
                touch keys/public.pem
            - name: Run tests
              run: |
                cargo test
